services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/app/Dockerfile
    container_name: ${PROJECT_NAME:-time_work}-app
    volumes:
    - ./app:/var/www/html
    ports:
    - '8000:8000'
    environment:
      APP_ENV: dev
      DATABASE_URL: 'mysql://symfony:symfony@db:3306/time_tracker?serverVersion=10.11&charset=utf8mb4'
    depends_on:
    - db

  db:
    image: mariadb:10.11
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: time_tracker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
    - '3306:3306'
    volumes:
    - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: time_tracker_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db

  app-front:
    build:
      context: ./
      dockerfile: ./.docker/app-front/Dockerfile
      args: 
        PROJECT_NAME: ${PROJECT_NAME:-time_work}
    container_name: ${PROJECT_NAME:-time_work}-front
    volumes:
    - ./app-front:/var/www/html
    ports:
    - '8001:8001'
    environment:
      APP_ENV: dev
    depends_on:
    - app

volumes:
  db_data:
